### ISSUE TITLE
Bug is not bug anymore...

### ISSUE THREAD

**Issue by osogi** [Escartem/Escartem#1]
> funny fact, this block of math breaks github markdown and every embed image beyond it won't load and return a violation in content security policy directive, i think this is bug, i'll report one day eventually, but that's why it's at the bottom

GitHub seems to have fixed this. 

[Proof](https://github.com/osogi/Escartem-README/tree/master)

![no-bug](https://github.com/user-attachments/assets/08426b6e-5560-44da-b8aa-8230368ba5f9)

**Comment by Escartem** [comment]
No way, i noticed that more than a year ago i never thought they would fix it and someone would notice and point it out, i guess it's fixed then -> https://github.com/Escartem/Escartem/commit/0175ef7b7ed9371909939ce74d69f2e08a3e3e83 (i left it at the bottom tho)

thanks :>
